openapi: 3.0.0
info:
  version: 1.0.0
  title: About Auth Service
externalDocs:
  description: Find more info here.
  url: https://github.com/andrew-boutin/about-auth-service
tags:
- name: entitlements
  description: An entitlement represents the right to access a part of the system.
- name: permissions
  description: A permission represents the right to do a single action in the system.
- name: roles
  description: A role represents a set of permissions required to fulfill a use case in the system.
- name: tenants
  description: A tenant provides a way to group common users and permissions.
- name: users
  description: A user is a single end user of the system.
paths:
  /entitlements:
    get:
      summary: Retrieve a list of entitlements.
      operationId: listEntitlements
      tags:
      - entitlements
      responses:
        '200':
          description: A list of entitlements.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entitlements'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: Create an entitlement.
      operationId: createEntitlement
      tags:
      - entitlements
      responses:
        '201':
          description: The created entitlement.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entitlement'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  '/entitlements/{id}':
    delete:
      summary: Delete a specific entitlement.
      operationId: deleteEntitlement
      tags:
      - entitlements
      parameters:
      - $ref: '#/components/parameters/IdPathParam'
      responses:
        '204':
          $ref: '#/components/responses/204'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    get:
      summary: Retrieve a specific entitlement.
      operationId: getEntitlement
      tags:
      - entitlements
      parameters:
      - $ref: '#/components/parameters/IdPathParam'
      responses:
        '200':
          description: The entitlement for the given id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entitlement'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Update a specific entitlement.
      operationId: updateEntitlement
      tags:
      - entitlements
      parameters:
      - $ref: '#/components/parameters/IdPathParam'
      responses:
        '200':
          description: The updated entitlement.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entitlement'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /permissions:
    get:
      summary: Retrieve a list of permissions.
      operationId: listPermissions
      tags:
      - permissions
      responses:
        '200':
          description: A list of permissions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permissions'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  '/permissions/{id}':
    get:
      summary: Retrieve a specific permission.
      operationId: getPermission
      tags:
      - permissions
      parameters:
      - $ref: '#/components/parameters/IdPathParam'
      responses:
        '200':
          description: The permission for the given id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permission'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /roles:
    get:
      summary: Retrieve a list of roles.
      operationId: listRoles
      tags:
      - roles
      parameters:
      - $ref: '#/components/parameters/TenantIdQueryParam'
      responses:
        '200':
          description: A list of roles.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Roles'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: Create a role.
      operationId: createRole
      tags:
      - roles
      responses:
        '201':
          description: The created role.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  '/roles/{id}':
    delete:
      summary: Delete a specific role.
      operationId: deleteRole
      tags:
      - roles
      parameters:
      - $ref: '#/components/parameters/IdPathParam'
      responses:
        '204':
          $ref: '#/components/responses/204'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    get:
      summary: Retrieve a specific role.
      operationId: getRole
      tags:
      - roles
      parameters:
      - $ref: '#/components/parameters/IdPathParam'
      responses:
        '200':
          description: The role for the given id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Update a specific role.
      operationId: updateRole
      tags:
      - roles
      parameters:
      - $ref: '#/components/parameters/IdPathParam'
      responses:
        '200':
          description: The updated role.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /tenants:
    get:
      summary: Retrieve a list of tenants.
      operationId: listTenants
      tags:
      - tenants
      responses:
        '200':
          description: A list of tenants.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenants'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: Create a tenant.
      operationId: createTenant
      tags:
      - tenants
      responses:
        '201':
          description: The created tenant.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  '/tenants/{id}':
    delete:
      summary: Delete a specific tenant.
      operationId: deleteTenant
      tags:
      - tenants
      parameters:
      - $ref: '#/components/parameters/IdPathParam'
      responses:
        '204':
          $ref: '#/components/responses/204'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    get:
      summary: Retrieve a specific tenant.
      operationId: getTenant
      tags:
      - tenants
      parameters:
      - $ref: '#/components/parameters/IdPathParam'
      responses:
        '200':
          description: The tenant for the given id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Update a specific tenant.
      operationId: updateTenant
      tags:
      - tenants
      parameters:
      - $ref: '#/components/parameters/IdPathParam'
      responses:
        '200':
          description: The updated tenant.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /users:
    get:
      summary: Retrieve a list of users.
      operationId: listUsers
      tags:
      - users
      parameters:
      - $ref: '#/components/parameters/IsSystemAdminQueryParam'
      - $ref: '#/components/parameters/IsTenantAdminQueryParam'
      - $ref: '#/components/parameters/TenantIdQueryParam'
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: Create a user.
      operationId: createUser
      tags:
      - users
      responses:
        '201':
          description: The created user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  '/users/{id}':
    delete:
      summary: Delete a specific user.
      operationId: deleteUser
      tags:
      - users
      parameters:
      - $ref: '#/components/parameters/IdPathParam'
      responses:
        '204':
          $ref: '#/components/responses/204'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    get:
      summary: Retrieve a specific user.
      operationId: getUser
      tags:
      - users
      parameters:
      - $ref: '#/components/parameters/IdPathParam'
      responses:
        '200':
          description: The user for the given id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Update a specific user.
      operationId: updateUser
      tags:
      - users
      parameters:
      - $ref: '#/components/parameters/IdPathParam'
      responses:
        '200':
          description: The updated user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
components:
  schemas:
    EntitlementSystemDefined:
      properties:
        id:
          type: integer
          format: int64
    EntitlementMutable:
      properties:
        name:
          type: string
          description: Unique name of the entitlement.
    Entitlement:
      type: object
      required:
      - name
      allOf:
      - $ref: '#/components/schemas/EntitlementSummary'
      properties:
        permissions:
          $ref: '#/components/schemas/Permissions'
    EntitlementSummary:
      type: object
      required:
      - name
      allOf:
      - $ref: '#/components/schemas/EntitlementSystemDefined'
      - $ref: '#/components/schemas/EntitlementMutable'
    Entitlements:
      type: array
      items:
        $ref: '#/components/schemas/EntitlementSummary'
    Error:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Permission:
      type: object
      properties:
        name:
          type: string
          description: Unique name of the permission.
        id:
          type: integer
          format: int64
    Permissions:
      type: array
      items:
        $ref: '#/components/schemas/Permission'
    RoleImmutable:
      properties:
        tenantId:
          type: integer
          format: int64
    RoleSystemDefined:
      properties:
        id:
          type: integer
          format: int64
    RoleMutable:
      properties:
        name:
          type: string
          description: Unique name, within the tenant, of the role.
    RoleSummary:
      type: object
      required:
      - name
      - tenantId
      allOf:
      - $ref: '#/components/schemas/RoleImmutable'
      - $ref: '#/components/schemas/RoleSystemDefined'
      - $ref: '#/components/schemas/RoleMutable'
    Role:
      type: object
      required:
      - name
      - tenantId
      allOf:
      - $ref: '#/components/schemas/RoleSummary'
      properties:
        permissions:
          $ref: '#/components/schemas/Permissions'
    Roles:
      type: array
      items:
        $ref: '#/components/schemas/RoleSummary'
    TenantSystemDefined:
      properties:
        id:
          type: integer
          format: int64
    TenantMutable:
      properties:
        name:
          type: string
          description: Unique name of the tenant.
    TenantSummary:
      type: object
      required:
      - name
      allOf:
      - $ref: '#/components/schemas/TenantSystemDefined'
      - $ref: '#/components/schemas/TenantMutable'
    Tenant:
      type: object
      required:
      - name
      allOf:
      - $ref: '#/components/schemas/TenantSummary'
      properties:
        entitlements:
          $ref: '#/components/schemas/Entitlements'
    Tenants:
      type: array
      items:
        $ref: '#/components/schemas/TenantSummary'
    UserImmutable:
      properties:
        tenantId:
          type: integer
          format: int64
    UserSystemDefined:
      properties:
        id:
          type: integer
          format: int64
    UserMutable:
      properties:
        name:
          type: string
          description: Unique name, within the tenant, of the user.
        isSystemAdmin:
          type: boolean
          description: Indicates if the user is an admin of the entire system.
        isTenantAdmin:
          type: boolean
          description: Indicates if the user is an admin of the tenant the user is a part of.
    User:
      type: object
      required:
      - name
      allOf:
      - $ref: '#/components/schemas/UserImmutable'
      - $ref: '#/components/schemas/UserSystemDefined'
      - $ref: '#/components/schemas/UserMutable'
    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'
  parameters:
    # Path parameters.
    IdPathParam:
      name: id
      in: path
      required: true
      description: The id of the resource to operate on.
      schema:
        type: string
    # Query parameters.
    IsSystemAdminQueryParam:
      name: isSystemAdmin
      in: query
      description: Filter the results for either all system admins or none.
      schema:
        type: boolean
    IsTenantAdminQueryParam:
      name: isTenantAdmin
      in: query
      description: Filter the results for either all tenant admins or none.
      schema:
        type: boolean
    TenantIdQueryParam:
      name: tenantId
      in : query
      description: The id of the tenant to filter the results for.
      schema:
        type: string
  responses:
    '204':
      description: No Content
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
