openapi: 3.0.0
info:
  version: 1.0.0
  title: About Auth Service
externalDocs:
  description: Find more info here.
  url: https://github.com/andrew-boutin/about-auth-service
tags:
- name: entitlements
  description: An entitlement represents the right to access a part of the system.
paths:
  /entitlements:
    get:
      summary: Retrieve a list of entitlements.
      operationId: listEntitlements
      tags:
      - entitlements
      responses:
        '200':
          description: A list of entitlements.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entitlements'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: Create an entitlement.
      operationId: createEntitlement
      tags:
      - entitlements
      responses:
        '201':
          description: The created entitlement.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entitlement'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  '/entitlements/{entitlementId}':
    delete:
      summary: Delete a specific entitlement.
      operationId: deleteEntitlement
      tags:
      - entitlements
      parameters:
      - $ref: '#/components/parameters/EntitlementIdPathParam'
      responses:
        '204':
          $ref: '#/components/responses/204'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    get:
      summary: Retrieve a specific entitlement.
      operationId: getEntitlement
      tags:
      - entitlements
      parameters:
      - $ref: '#/components/parameters/EntitlementIdPathParam'
      responses:
        '200':
          description: The entitlement for the given id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entitlement'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Update a specific entitlement.
      operationId: updateEntitlement
      tags:
      - entitlements
      parameters:
      - $ref: '#/components/parameters/EntitlementIdPathParam'
      responses:
        '200':
          description: The updated entitlement.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entitlement'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
components:
  schemas:
    EntitlementSystemDefined:
      properties:
        id:
          type: integer
          format: int64
    EntitlementMutable:
      properties:
        name:
          type: string
          description: Unique name of the entitlement.
    Entitlement:
      type: object
      required:
      - name
      allOf:
      - $ref: '#/components/schemas/EntitlementSystemDefined'
      - $ref: '#/components/schemas/EntitlementMutable'
    Entitlements:
      type: array
      items:
        $ref: '#/components/schemas/Entitlement'
    Error:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  parameters:
    EntitlementIdPathParam:
      name: entitlementId
      in: path
      required: true
      description: The id of the entitlement to operate on.
      schema:
        type: string
  responses:
    '204':
      description: No Content
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
